# frozen_string_literal: true

# Fisco.io - Core Engine
# Framework de Administración Tributaria - Event-sourced tax administration

source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 8.0"
gem "puma", "~> 6.0"
gem "pg", "~> 1.5"
gem "redis", "~> 5.0"
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "rspec-rails", "~> 7.0", group: :test
gem "simplecov", "~> 0.22", group: :test, require: false
gem "rubocop", "~> 1.60", group: :development
gem "good_job", "~> 4.0"

# Value objects / domain types (optional)
# gem "dry-struct"
# gem "dry-types"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
